### ISSUE TITLE
how to predict new data with your code?

### ISSUE THREAD

**Issue by sleric** [bluekingsong/simple-gbdt#1]

**Comment by bluekingsong** [comment]
I didn't implement the prediction function directly. However, you can change the code slightly in gbt.py( line 17-20 ). The function "test" in model.py could help you.

**Comment by bound2020** [comment]
How long did it take to train on the training data?

**Comment by bluekingsong** [comment]
it depends what data you are training. to be frank, the code is slow and just for demonstrating how to implement GBDT. for fast training, i recommend you https://github.com/Microsoft/LightGBM.
