### ISSUE TITLE
Using len(self.field_type['label']) to get the class number is a bug.

### ISSUE THREAD

**Issue by liudragonfly** [bluekingsong/simple-gbdt#2]
Hi,
You use len(self.field_type['label']) to get the class number. But when the label works with float(label), len(self.field_type['label']) will be 0. That is a bug.

**Comment by bluekingsong** [comment]
thanks, sorry that i did not see my project for a long time. for good GBDT package, i recommend you https://github.com/Microsoft/LightGBM, it very fast, trust me.
